use once_cell::sync::Lazy;
pub struct IconSet {
    pub palette: &'static str,
    pub star: &'static str,
    pub smooth_star: &'static str,
    pub hollow_star: &'static str,
    pub badge_star: &'static str,
    pub triangle_right: &'static str,
    pub triangle_down: &'static str,
    pub circle: &'static str,
    pub square: &'static str,
    pub smooth_square: &'static str,
    pub check: &'static str,
    pub warning: &'static str,
    pub error: &'static str,
    pub sun: &'static str,
    pub moon: &'static str,
}

pub static ICONS: Lazy<IconSet> = Lazy::new(|| IconSet{
    palette: "",
    star: "󰓎",
    smooth_star: "",
    hollow_star: "",
    badge_star: "󰓏",
    triangle_right: "󰁔",
    triangle_down: "󰁕",
    circle: "󰀀",
    square: "󰝤",
    smooth_square: "",
    check: "󰄬",
    warning: "󰀦",
    error: "󰅚",
    sun: "",
    moon: "",
});
